name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
       # with:
       #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build Hugo
        run: hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify

      - name: Deploy to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }}
          external_repository: eallion/qinzheyu
          PUBLISH_BRANCH: public
          PUBLISH_DIR: ./public
          allow_empty_commit: true
          commit_message: ${{ GitHub.event.head_commit.message }}

      # 部署前删掉一些无用文件以节省流量
      - name: Delete images
        run: |
          rm -rf public/images
          rm -rf public/photos

      # 部署到阿里云 OSS
      #- name: Deploy to OSS
      #  uses: saltbo/uptoc@master
      #  with:
      #    driver: oss
      #    region: cn-shanghai
      #    bucket: eallion-com
      #    dist: public
      #  env:
      #    UPTOC_UPLOADER_AK: ${{ secrets.ACCESS_KEY_ID }}
      #    UPTOC_UPLOADER_SK: ${{ secrets.ACCESS_KEY_SECRET }}

      # 部署到腾讯云 COS
      #- name: Deploy to COS
      #  uses: saltbo/uptoc@master
      #  with:
      #    driver: cos
      #    region: ap-shanghai
      #    bucket: ${{ secrets.COS_CN_BUCKET }}
      #    dist: public
      #  env:
      #    UPTOC_UPLOADER_AK: ${{ secrets.SECRET_COS_ID }}
      #    UPTOC_UPLOADER_SK: ${{ secrets.SECRET_COS_KEY }}